# Generated by Django 4.1.2 on 2022-10-15 09:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('intro', models.CharField(blank=True, max_length=250, null=True, verbose_name='Подзаголовок')),
                ('body', wagtail.fields.StreamField([('rtfblock', wagtail.blocks.RichTextBlock(label='Текст')), ('embedblock', wagtail.embeds.blocks.EmbedBlock(label='Ссылка'))], blank=True, use_json_field=None, verbose_name='Содержимое')),
                ('author', models.CharField(blank=True, max_length=250, null=True, verbose_name='Автор')),
                ('bgimg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Задний фон')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
