# Generated by Django 4.1.2 on 2022-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_eventpage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='joinbtn',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Участвовать ссылка'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='reviewbtn',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Оставить отзыв ссылка'),
        ),
    ]
