# Generated by Django 4.1.2 on 2022-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventpage_joinbtn_eventpage_reviewbtn'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='calendar',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='ссылка на календарь c тегом <frame>'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='joinbtn',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Участвовать ссылка'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='reviewbtn',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Оставить отзыв ссылка'),
        ),
    ]
