# Generated by Django 4.1.2 on 2022-11-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventpage_calendar_alter_eventpage_joinbtn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='calendar',
        ),
    ]
