# Generated by Django 4.1.2 on 2022-10-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='carousel_image',
            new_name='photo',
        ),
    ]
