# Generated by Django 4.1.2 on 2022-10-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('blog', '0002_blogpage_author_alter_blogpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='bgimg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
