# Generated by Django 4.1.2 on 2022-10-15 08:23

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogindexpage_bgimg_blogindexpage_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('figcaptionblock', wagtail.blocks.StructBlock([('caption', wagtail.blocks.CharBlock()), ('figure', wagtail.images.blocks.ImageChooserBlock(label='Изображение'))])), ('rtfblock', wagtail.blocks.RichTextBlock(label='Текст')), ('embedblock', wagtail.embeds.blocks.EmbedBlock(label='Ссылка'))], blank=True, use_json_field=None, verbose_name='Содержимое'),
        ),
    ]
