# Generated by Django 4.1.2 on 2022-10-09 09:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='strbody',
            field=wagtail.fields.StreamField([('figcaptionblock', wagtail.blocks.StructBlock([('caption', wagtail.blocks.CharBlock()), ('figure', wagtail.images.blocks.ImageChooserBlock(label='Изображение'))])), ('rtfblock', wagtail.blocks.RichTextBlock(label='Текст')), ('imgblock', wagtail.images.blocks.ImageChooserBlock(label='Изображение', template='blocks/imgblock.html')), ('embedblock', wagtail.embeds.blocks.EmbedBlock(label='Ссылка'))], blank=True, use_json_field=None, verbose_name='Содержимое'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('carousel_caption', models.CharField(blank=True, default='', max_length=600, null=True, verbose_name='Текст Слайда')),
                ('carousel_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение слайда')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
