# Generated by Django 4.1.2 on 2022-10-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_strbody_homepage_subtitle_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='carousel_title',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Текст Слайда'),
        ),
    ]
