# Generated by Django 4.1.2 on 2022-10-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_footer_alter_slider_carousel_caption_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
