# Generated by Django 4.1.2 on 2022-10-15 08:23

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='strbody',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Содержание'),
        ),
    ]
