# Generated by Django 4.1.2 on 2022-11-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_strbody_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='calendar',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='ссылка на календарь c тегом <frame>'),
        ),
    ]
