# Generated by Django 4.1.2 on 2022-11-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='calendar',
        ),
    ]
